tarot_deck = [
    {"name": "The Fool", "meaning": "Beginnings, Innocence", "image": "Fool.gif"},
    {"name": "The Magician", "meaning": "Manifestation, Will", "image": "Magician.gif"},
    {"name": "The High Priestess", "meaning": "Mystery, Intuition", "image": "HighPriestess.gif"},
    {"name": "The Empress", "meaning": "Fertility, Abundance", "image": "Empress.gif"},
    {"name": "The Emperor", "meaning": "Authority, Structure", "image": "Emperor.gif"},
    {"name": "The Hierophant", "meaning": "Tradition, Guidance", "image": "Hierophant.gif"},
    {"name": "The Lovers", "meaning": "Choices, Union", "image": "Lovers.gif"},
    {"name": "The Chariot", "meaning": "Control, Willpower", "image": "Chariot.gif"},
    {"name": "Strength", "meaning": "Courage, Influence", "image": "Strength.gif"},
    {"name": "The Hermit", "meaning": "Introspection, Solitude", "image": "Hermit.gif"},
    {"name": "Wheel of Fortune", "meaning": "Cycles, Fate", "image": "WheelOfFortune.gif"},
    {"name": "Justice", "meaning": "Fairness, Truth", "image": "Justice.gif"},
    {"name": "The Hanged Man", "meaning": "Surrender, Perspective", "image": "HangedMan.gif"},
    {"name": "Death", "meaning": "Transformation, Transition", "image": "Death.gif"},
    {"name": "Temperance", "meaning": "Balance, Moderation", "image": "Temperance.gif"},
    {"name": "The Devil", "meaning": "Bondage, Materialism", "image": "Devil.gif"},
    {"name": "The Tower", "meaning": "Upheaval, Revelation", "image": "Tower.gif"},
    {"name": "The Star", "meaning": "Hope, Inspiration", "image": "Star.gif"},
    {"name": "The Moon", "meaning": "Intuition, Mystery", "image": "Moon.gif"},
    {"name": "The Sun", "meaning": "Joy, Success", "image": "Sun.gif"},
    {"name": "Judgment", "meaning": "Reckoning, Absolution", "image": "Judgment.gif"},
    {"name": "The World", "meaning": "Completion, Integration", "image": "World.gif"},
    {"name": "Ace of Wands", "meaning": "Inspiration, Potential", "image": "Wands01.gif"},
    {"name": "Two of Wands", "meaning": "Planning, Future", "image": "Wands02.gif"},
    {"name": "Three of Wands", "meaning": "Expansion, Foresight", "image": "Wands03.gif"},
    {"name": "Four of Wands", "meaning": "Celebration, Harmony", "image": "Wands04.gif"},
    {"name": "Five of Wands", "meaning": "Conflict, Competition", "image": "Wands05.gif"},
    {"name": "Six of Wands", "meaning": "Victory, Recognition", "image": "Wands06.gif"},
    {"name": "Seven of Wands", "meaning": "Defense, Perseverance", "image": "Wands07.gif"},
    {"name": "Eight of Wands", "meaning": "Speed, Action", "image": "Wands08.gif"},
    {"name": "Nine of Wands", "meaning": "Resilience, Courage", "image": "Wands09.gif"},
    {"name": "Ten of Wands", "meaning": "Burden, Responsibility", "image": "Wands10.gif"},
    {"name": "Page of Wands", "meaning": "Discovery, Enthusiasm", "image": "Wands11.gif"},
    {"name": "Knight of Wands", "meaning": "Adventure, Energy", "image": "Wands12.gif"},
    {"name": "Queen of Wands", "meaning": "Confidence, Determination", "image": "Wands13.gif"},
    {"name": "King of Wands", "meaning": "Leadership, Vision", "image": "Wands14.gif"},
    {"name": "Ace of Cups", "meaning": "Love, Compassion", "image": "Cups01.gif"},
    {"name": "Two of Cups", "meaning": "Connection, Attraction", "image": "Cups02.gif"},
    {"name": "Three of Cups", "meaning": "Friendship, Celebration", "image": "Cups03.gif"},
    {"name": "Four of Cups", "meaning": "Apathy, Contemplation", "image": "Cups04.gif"},
    {"name": "Five of Cups", "meaning": "Loss, Grief", "image": "Cups05.gif"},
    {"name": "Six of Cups", "meaning": "Nostalgia, Innocence", "image": "Cups06.gif"},
    {"name": "Seven of Cups", "meaning": "Choices, Illusion", "image": "Cups07.gif"},
    {"name": "Eight of Cups", "meaning": "Departure, Search", "image": "Cups08.gif"},
    {"name": "Nine of Cups", "meaning": "Satisfaction, Pleasure", "image": "Cups09.gif"},
    {"name": "Ten of Cups", "meaning": "Fulfillment, Joy", "image": "Cups10.gif"},
    {"name": "Page of Cups", "meaning": "Imagination, Curiosity", "image": "Cups11.gif"},
    {"name": "Knight of Cups", "meaning": "Romance, Idealism", "image": "Cups12.gif"},
    {"name": "Queen of Cups", "meaning": "Empathy, Care", "image": "Cups13.gif"},
    {"name": "King of Cups", "meaning": "Compassion, Control", "image": "Cups14.gif"},
    {"name": "Ace of Swords", "meaning": "Clarity, Breakthrough", "image": "Swords01.gif"},
    {"name": "Two of Swords", "meaning": "Stalemate, Uncertainty", "image": "Swords02.gif"},
    {"name": "Three of Swords", "meaning": "Heartbreak, Sorrow", "image": "Swords03.gif"},
    {"name": "Four of Swords", "meaning": "Rest, Contemplation", "image": "Swords04.gif"},
    {"name": "Five of Swords", "meaning": "Conflict, Defeat", "image": "Swords05.gif"},
    {"name": "Six of Swords", "meaning": "Transition, Healing", "image": "Swords06.gif"},
    {"name": "Seven of Swords", "meaning": "Strategy, Deception", "image": "Swords07.gif"},
    {"name": "Eight of Swords", "meaning": "Restriction, Confusion", "image": "Swords08.gif"},
    {"name": "Nine of Swords", "meaning": "Anxiety, Fear", "image": "Swords09.gif"},
    {"name": "Ten of Swords", "meaning": "End, Release", "image": "Swords10.gif"},
    {"name": "Page of Swords", "meaning": "Curiosity, Vigilance", "image": "Swords11.gif"},
    {"name": "Knight of Swords", "meaning": "Action, Impulsiveness", "image": "Swords12.gif"},
    {"name": "Queen of Swords", "meaning": "Independence, Perception", "image": "Swords13.gif"},
    {"name": "King of Swords", "meaning": "Authority, Ethics", "image": "Swords14.gif"},
    {"name": "Ace of Pentacles", "meaning": "Opportunity, Prosperity", "image": "Pentacles01.gif"},
    {"name": "Two of Pentacles", "meaning": "Balance, Adaptability", "image": "Pentacles02.gif"},
    {"name": "Three of Pentacles", "meaning": "Teamwork, Skill", "image": "Pentacles03.gif"},
    {"name": "Four of Pentacles", "meaning": "Security, Control", "image": "Pentacles04.gif"},
    {"name": "Five of Pentacles", "meaning": "Hardship, Isolation", "image": "Pentacles05.gif"},
    {"name": "Six of Pentacles", "meaning": "Generosity, Charity", "image": "Pentacles06.gif"},
    {"name": "Seven of Pentacles", "meaning": "Patience, Investment", "image": "Pentacles07.gif"},
    {"name": "Eight of Pentacles", "meaning": "Dedication, Mastery", "image": "Pentacles08.gif"},
    {"name": "Nine of Pentacles", "meaning": "Abundance, Luxury", "image": "Pentacles09.gif"},
    {"name": "Ten of Pentacles", "meaning": "Wealth, Legacy", "image": "Pentacles10.gif"},
    {"name": "Page of Pentacles", "meaning": "Manifestation, Skill Development", "image": "Pentacles11.gif"},
    {"name": "Knight of Pentacles", "meaning": "Efficiency, Dedication", "image": "Pentacles12.gif"},
    {"name": "Queen of Pentacles", "meaning": "Nurturing, Abundance", "image": "Pentacles13.gif"},
    {"name": "King of Pentacles", "meaning": "Success, Stability", "image": "Pentacles14.gif"},
]